apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - image: IMAGE_URL
          name: auth
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: connectionString
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: jwtSecret
            - name: JWT_EXPIRATION
              value: '3600'
            - name: TCP_PORT
              value: '3101'
            - name: HTTP_PORT
              value: '3001'
          ports:
            - containerPort: 3101
            - containerPort: 3001
