services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: npm run start:dev reservations
    #command: npm run start:debug reservations
    env_file:
      - ./apps/reservations/.env
    ports:
      - '3000:3000'
      #- '9229:9229'
    volumes:
      - .:/usr/src/app
    environment:
      - TZ=Europe/Belgrade
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
    environment:
      - TZ=Europe/Belgrade
  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: npm run start:dev payments
    env_file:
      - ./apps/payments/.env
    ports:
      - '3002:3002'
    volumes:
      - .:/usr/src/app
    environment:
      - TZ=Europe/Belgrade
  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    command: npm run start:dev notifications
    env_file:
      - ./apps/notifications/.env
    ports:
      - '3003:3003'
    volumes:
      - .:/usr/src/app
    environment:
      - TZ=Europe/Belgrade
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      - TZ=Europe/Belgrade
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: default
      POSTGRES_PASSWORD: postgres
      TZ: Europe/Belgrade
