services:
  e2e:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./specs:/usr/src/app/specs
    depends_on:
      - reservations
      - auth
      - payments
      - notifications
      - mongo
  reservations:
    image: IMAGE_URL
    env_file:
      - ../apps/reservations/.env
    ports:
      - '3000:3000'
  auth:
    image: IMAGE_URL
    env_file:
      - ../apps/auth/.env
    ports:
      - '3001:3001'
  payments:
    image: IMAGE_URL
    ports:
      - '3002:3002'
    env_file:
      - ../apps/payments/.env
  notifications:
    image: IMAGE_URL
    ports:
      - '3003:3003'
    env_file:
      - ../apps/notifications/.env
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      - TZ=Europe/Belgrade
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: default
      POSTGRES_PASSWORD: postgres
      TZ: Europe/Belgrade

