apiVersion: v1
kind: Service
metadata:
  labels:
    app: payments
  name: payments
spec:
  ports:
    - name: 'tcp'
      port: 3102
      protocol: TCP
      targetPort: 3102
  selector:
    app: payments
  type: ClusterIP
